### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by sandrobonazzola** [operate-first/ai-for-cloud-ops#12]
This repository is lacking licensing information. As such, everything included in this repo is "All rights reserved".
Please note that in order to re-license this project you'll legally need ack from all existing contributors.

**Comment by abyrne55** [comment]
Closed by [bdbda6e](https://github.com/operate-first/ai-for-cloud-ops/commit/bdbda6e7b850028ffd91220625ec765b01e38416)
